/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class IMAPMailboxes, MailboxUid, NSArray, NSString;

@interface _IMAPMailboxEntry : NSObject
{
    NSString *_name;
    NSString *_path;
    BOOL _subscribed;
    NSArray *_children;
    NSArray *_filteredChildren;
    MailboxUid *_uid;
    BOOL _isNoSelect;
    BOOL _hasEnabledDescendants;
    _IMAPMailboxEntry *_parent;
    IMAPMailboxes *_controller;
}

- (void)dealloc;
- (long long)compare:(id)arg1;
- (id)filteredChildren;
- (BOOL)isPathValidForCurrentFilter;
- (BOOL)isValidForCurrentFilter;
@property(nonatomic) IMAPMailboxes *_controller; // @synthesize _controller;
@property(retain, nonatomic) _IMAPMailboxEntry *_parent; // @synthesize _parent;
@property(nonatomic) BOOL _hasEnabledDescendants; // @synthesize _hasEnabledDescendants;
@property(nonatomic) BOOL _isNoSelect; // @synthesize _isNoSelect;
@property(retain, nonatomic) MailboxUid *_uid; // @synthesize _uid;
@property(retain, nonatomic) NSArray *_filteredChildren; // @synthesize _filteredChildren;
@property(retain, nonatomic) NSArray *_children; // @synthesize _children;
@property(nonatomic) BOOL _subscribed; // @synthesize _subscribed;
@property(retain, nonatomic) NSString *_path; // @synthesize _path;
@property(retain, nonatomic) NSString *_name; // @synthesize _name;

@end

