/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSArray, NSAttributedString, NSMutableArray, NSString;

@interface _WebComposeMessageContents : NSObject
{
    int sendFormat;
    NSAttributedString *plainText;
    NSString *topLevelHtmlString;
    NSMutableArray *attachmentsAndHtmlStrings;
    NSMutableArray *urlsForAttachmentsAndHtmlStrings;
    NSArray *_todoIDs;
}

- (void)dealloc;
- (void)addAttachmentOrHtmlString:(id)arg1 withURL:(id)arg2;
- (id)description;
@property(retain) NSArray *todoIDs; // @synthesize todoIDs=_todoIDs;
@property(retain, nonatomic) NSMutableArray *urlsForAttachmentsAndHtmlStrings; // @synthesize urlsForAttachmentsAndHtmlStrings;
@property(retain, nonatomic) NSMutableArray *attachmentsAndHtmlStrings; // @synthesize attachmentsAndHtmlStrings;
@property(retain, nonatomic) NSString *topLevelHtmlString; // @synthesize topLevelHtmlString;
@property(retain, nonatomic) NSAttributedString *plainText; // @synthesize plainText;
@property(nonatomic) int sendFormat; // @synthesize sendFormat;

@end

