/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class MessageAttachmentViewController, NSString, NSURL, NSWindow;

@interface AttachmentQueueEntry : NSObject
{
    NSWindow *window;
    MessageAttachmentViewController *attachmentController;
    int reason;
    NSString *attachDir;
    union {
        NSURL *applicationURL;
        NSString *savePath;
    } opSpecific;
}

+ (id)newWithWindow:(id)arg1 attachmentController:(id)arg2 reason:(int)arg3 opSpecific:(id)arg4 attachmentDirectory:(id)arg5;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSString *attachDir; // @synthesize attachDir;
@property(nonatomic) int reason; // @synthesize reason;
@property(retain, nonatomic) MessageAttachmentViewController *attachmentController; // @synthesize attachmentController;
@property(retain, nonatomic) NSWindow *window; // @synthesize window;

@end

