/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class ABAddressBook, CompletionController, NSMutableArray;

@interface AutocompletionResultsAccumulator : NSObject
{
    CompletionController *_completionController;
    NSMutableArray *_mailRecents;
    NSMutableArray *_regularRecords;
    long long _numberOfLocalSearches;
    long long _numberOfRemoteSearches;
    ABAddressBook *_addressBookForSearching;
}

- (id)init;
- (void)dealloc;
@property CompletionController *completionController;
- (id)copyCompletionController;
- (void)reset;
- (void)expectLocalSearches:(long long)arg1 remoteSearches:(long long)arg2 addressBook:(id)arg3;
- (BOOL)searchOperationIsValid:(id)arg1;
- (void)searchOperationDidFinish:(id)arg1;
- (void)searchOperation:(id)arg1 foundRecords:(id)arg2;
- (void)sendLocalSearchResultsToCompletionController:(id)arg1;
@property(retain) ABAddressBook *addressBookForSearching; // @synthesize addressBookForSearching=_addressBookForSearching;
@property(readonly) NSMutableArray *regularRecords; // @synthesize regularRecords=_regularRecords;
@property(readonly) NSMutableArray *mailRecents; // @synthesize mailRecents=_mailRecents;

@end

