/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSButton.h"

@class NSImage;

@interface BorderlessButton : NSButton
{
    NSImage *activeImage;
    NSImage *inactiveImage;
}

- (BOOL)isOpaque;
- (void)dealloc;
- (void)setEnabled:(BOOL)arg1;
@property(retain) NSImage *inactiveImage; // @synthesize inactiveImage;
@property(retain) NSImage *activeImage; // @synthesize activeImage;

@end

