/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSFont, NSMutableDictionary;

@interface DateCell : NSTextFieldCell
{
    NSFont *_lastFont;
    NSMutableDictionary *_drawingAttributes;
    int _dateDetailLevel;
    double _lastWidth;
    _Bool _lastStringWasRTL;
    BOOL _forceTextColor;
}

+ (void)initialize;
+ (void)resetDateFormats;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setFont:(id)arg1;
- (void)setTextColor:(id)arg1;
- (void)setAlignment:(unsigned long long)arg1;
- (void)setNeedsDisplay:(BOOL)arg1;
- (BOOL)underlinesText;
- (void)setUnderlinesText:(BOOL)arg1;
- (void)updateLocale;
- (void)setTimeIntervalSince1970:(double)arg1;
- (void)setObjectValue:(id)arg1;
- (double)minimumWidth;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)stringValue;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1 forParameter:(id)arg2;
@property(nonatomic) BOOL forceTextColor; // @synthesize forceTextColor=_forceTextColor;

@end

