/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "DOMNode.h"

@class DOMHTMLElement, DOMRange, NSArray, NSString;

@interface DOMNode (ToDoExtras)
@property(readonly) DOMHTMLElement *previousToDoElement;
@property(readonly) DOMHTMLElement *nextToDoElement;
- (id)closestToDoElementDownstream:(char *)arg1;
- (id)_elementsWithIDPrefix:(id)arg1 className:(id)arg2;
@property(readonly) NSArray *todoIDs;
@property(readonly) NSArray *todoElements;
@property(readonly) NSArray *frozenToDoIDs;
@property(readonly) NSArray *frozenToDoElements;
@property(readonly) DOMHTMLElement *enclosingToDoElement;
@property(readonly) BOOL isToDoElement;
@property(readonly) BOOL isFrozenToDoElement;
@property(readonly) BOOL isToDoBodyElement;
@property(readonly) BOOL isToDoContentElement;
@property(readonly) DOMHTMLElement *frozenToDoContentElement;
@property(readonly) DOMRange *rangeBeforeToDo;
@property(readonly) DOMRange *rangeAfterToDo;
@property(readonly) DOMRange *visualRangeBeforeToDo;
@property(readonly) DOMRange *visualRangeAfterToDo;
@property(readonly) DOMRange *contentRange;
@property(readonly) DOMRange *todoUserContentRange;
@property(copy) NSString *todoUserContent;
@property(readonly) DOMHTMLElement *todoBodyElement;
@property(readonly) DOMHTMLElement *todoCheckboxElement;
@property(readonly) DOMHTMLElement *todoDateElement;
- (id)todoContentElementIfExists;
@property(readonly) BOOL containsToDoContentElement;
@property(readonly) DOMHTMLElement *todoContentElement;
@property(readonly) DOMHTMLElement *todoRowElement;
@property(readonly) DOMHTMLElement *todoDeleteElement;
@property(readonly) DOMHTMLElement *todoDeleteDivElement;
- (void)flattenTodoElements;
@property BOOL todoDeleteButtonIsVisible;
@end

