/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "DOMRange.h"

@class DOMHTMLElement, NSArray;

@interface DOMRange (ToDoExtras)
@property(readonly) NSArray *entireTodos;
- (BOOL)_hasToDoElements:(id)arg1 partialOK:(BOOL)arg2;
@property(readonly) DOMHTMLElement *enclosingToDoElement;
@property(readonly) BOOL isWithinToDo;
@property(readonly) BOOL containsAnyToDos;
@property(readonly) BOOL containsEntireToDos;
@property(readonly) NSArray *anyTodoElements;
@property(readonly) NSArray *entireTodoElements;
- (BOOL)containsToDoCheckbox:(id)arg1;
- (BOOL)containsToDoCheckboxAndContent:(id)arg1;
@property(readonly) DOMRange *effectiveToDoRangeIfDifferent;
@end

