/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DynamicErrorWindowDelegate <NSObject>
- (BOOL)displayIndeterminateProgress;
- (id)errorMessageForErrorDiagnosis:(unsigned long long)arg1;
- (id)errorDescriptionForErrorDiagnosis:(unsigned long long)arg1;
- (id)leftButtonTextForErrorDiagnosis:(unsigned long long)arg1;
- (id)rightButtonTextForErrorDiagnosis:(unsigned long long)arg1;
- (void)leftActionSelectedWithDiagnosis:(unsigned long long)arg1;
- (void)rightActionSelectedWithDiagnosis:(unsigned long long)arg1;
- (unsigned long long)helpTopicForDiagnosis:(unsigned long long)arg1;
@end

