/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray;

@interface FilteredListInfo : NSObject
{
    NSMutableArray *filteredMessages;
    NSArray *changedMessages;
    NSMutableArray *filteredThreads;
    NSArray *changedThreads;
    NSDictionary *changedFlags;
    NSArray *messagesFilteredIn;
    NSArray *messagesFilteredOut;
    int taskType;
}

+ (id)infoForType:(int)arg1;
- (void)dealloc;
@property int taskType; // @synthesize taskType;
@property(retain) NSArray *messagesFilteredOut; // @synthesize messagesFilteredOut;
@property(retain) NSArray *messagesFilteredIn; // @synthesize messagesFilteredIn;
@property(retain) NSDictionary *changedFlags; // @synthesize changedFlags;
@property(retain) NSArray *changedThreads; // @synthesize changedThreads;
@property(retain) NSMutableArray *filteredThreads; // @synthesize filteredThreads;
@property(retain) NSArray *changedMessages; // @synthesize changedMessages;
@property(retain) NSMutableArray *filteredMessages; // @synthesize filteredMessages;

@end

