/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@interface FScriptProxy : NSObject
{
}

+ (void)loadFScriptFramework;
+ (void)initialize;
+ (Class)interpreterClass;
+ (Class)interpreterViewClass;
+ (void)loadGraphicalInterpreter;
+ (void)executeScript:(id)arg1;

@end

