/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "Assistant.h"

@class LibraryUpgrader, NSButton, NSTextField, NSView;

@interface LibraryUpgradeAssistant : Assistant
{
    NSView *introView;
    NSView *softwareUpdateIntroView;
    NSView *patienceView;
    NSView *epilogueView;
    NSView *errorView;
    NSTextField *showNewFeaturesText;
    NSButton *showNewFeaturesButton;
    LibraryUpgrader *libraryUpgrader;
    NSView *currentView;
    int state;
    BOOL isPointReleaseUpgrade;
}

- (id)libraryUpgrader;
- (void)setLibraryUpgrader:(id)arg1;
- (id)initWithAssistentManager:(id)arg1;
- (void)dealloc;
- (id)windowTitle;
- (int)state;
- (void)setState:(int)arg1;
- (id)currentView;
- (void)setCurrentView:(id)arg1;
- (void)start;
- (void)stop;
- (void)goForward;
- (void)requestUserAttention;
- (void)upgrader:(id)arg1 didRunForObject:(id)arg2;
- (void)upgrader:(id)arg1 didFailRunWithError:(id)arg2 forObject:(id)arg3;
- (void)showNewFeatures:(id)arg1;

@end

