/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSCloneCommand.h"

@interface MailCopyCommand : NSCloneCommand
{
    id _originalScriptCommandDefinition;
}

- (id)initWithCommandDescription:(id)arg1;
- (void)dealloc;
- (id)performDefaultImplementation;

@end

