/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptSignature)
- (void)insertInSignatures:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInSignatures:(id)arg1;
- (void)removeFromSignaturesAtIndex:(unsigned long long)arg1;
@end

