/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptAccountPreferences)
- (void)_insertInAccounts:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInAccounts:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInAccounts:(id)arg1;
- (void)insertInIToolsAccounts:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInIToolsAccounts:(id)arg1;
- (void)insertInImapAccounts:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInImapAccounts:(id)arg1;
- (void)insertInPopAccounts:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInPopAccounts:(id)arg1;
- (void)removeFromAccountsAtIndex:(unsigned long long)arg1;
- (id)deliveryAccounts;
@end

