/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "WebViewEditor.h"

#import "DOMEventListener-Protocol.h"

@class DOMNode, NSArray, NSMutableArray;

@interface MailWebViewEditor : WebViewEditor <DOMEventListener>
{
    BOOL needToFinishMakingPlainAfterRemovingStationery;
    NSArray *backgroundTilingElements;
    NSArray *backgroundTilingDivs;
    NSArray *backgroundTilingFixedSizes;
    NSMutableArray *uneditedEditableElements;
    NSMutableArray *editedEditableElements;
    DOMNode *editableElementWithMouseDown;
    BOOL shouldAttachFilesAtEnd;
    BOOL isDeletingAllEncompassingSelection;
}

@property(readonly) NSArray *insertablePasteboardTypes;
- (void)prepareToGoAway;
- (void)dealloc;
- (void)setUp;
- (void)setBackEnd:(id)arg1;
- (BOOL)allowQuoting;
- (void)setAllowsRichText:(BOOL)arg1;
- (id)alertForConvertingToRichText;
- (BOOL)webView:(id)arg1 shouldInsertAttachments:(id)arg2 context:(id)arg3;
- (BOOL)isOkayToLoadStationery;
- (void)continueCannotInsertStationery:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;
@property BOOL shouldAttachFilesAtEnd; // @synthesize shouldAttachFilesAtEnd;
- (void)_insertAttributedStringOfAttachments:(id)arg1 allAttachmentsAreOkay:(BOOL)arg2;
- (void)continueShouldInsertAttachments:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;
- (BOOL)isOkayToInsertAttachment:(id)arg1;
- (void)insertAttributedStringOfAttachments:(id)arg1 allAttachmentsAreOkay:(BOOL)arg2;
- (void)continueInsertAttributedStringOfAttachments:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;
- (BOOL)webView:(id)arg1 canInsertFromPasteboard:(id)arg2 forDrag:(BOOL)arg3;
- (void)prepareToRemoveStationery;
- (void)webViewDidLoadStationery:(id)arg1;
- (void)stationeryDidFinishLoadingResources:(id)arg1;
- (void)handleEvent:(id)arg1;
- (void)doOrUndoEditingInSignatureWithInfo:(id)arg1;
- (id)editedEditableElements;
- (void)mouseDownDidHappen:(id)arg1 inWebView:(id)arg2;
- (void)mouseUpDidHappen:(id)arg1 inWebView:(id)arg2;
- (void)webViewDidChange:(id)arg1;
- (id)replaceOldSignatureWithNewSignature:(id)arg1;
- (void)webViewDidChangeSelection:(id)arg1;
- (BOOL)webView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)insertNewline:(id)arg1;
- (void)webView:(id)arg1 didWriteSelectionToPasteboard:(id)arg2;
- (void)changeDocumentBackgroundColorWithContext:(id)arg1;
- (void)continueChangeDocumentBackgroundColor:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;
@property(retain) NSArray *backgroundTilingFixedSizes; // @synthesize backgroundTilingFixedSizes;
@property(retain) NSArray *backgroundTilingDivs; // @synthesize backgroundTilingDivs;
@property(retain) NSArray *backgroundTilingElements; // @synthesize backgroundTilingElements;

@end

