/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSSplitView.h"

@interface MailVerticalSplitView : NSSplitView
{
}

- (void)setPosition:(double)arg1 ofDividerAtIndex:(long long)arg2 byAnimating:(BOOL)arg3;
- (void)hideFirstSubviewRestoringFrameTo:(id)arg1;

@end

