/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (AppleScriptFontsAndColorsPreferences)
- (void)fontsAndColorsPreferencesDidChange:(BOOL)arg1;
- (void)fontsAndColorsPreferencesDidChange;
- (void)setMessageFont:(id)arg1 size:(double)arg2;
- (void)setFixedPitchFont:(id)arg1 size:(double)arg2;
- (BOOL)colorQuotedText;
- (void)setColorQuotedText:(BOOL)arg1;
- (id)messageListFont;
- (void)setMessageListFont:(id)arg1;
- (double)messageListFontSize;
- (void)setMessageListFontSize:(double)arg1;
- (id)messageFont;
- (void)setMessageFont:(id)arg1;
- (double)messageFontSize;
- (void)setMessageFontSize:(double)arg1;
- (BOOL)useFixedWidthFont;
- (void)setUseFixedWidthFont:(BOOL)arg1;
- (id)fixedWidthFont;
- (void)setFixedWidthFont:(id)arg1;
- (double)fixedWidthFontSize;
- (void)setFixedWidthFontSize:(double)arg1;
- (void)setQuotingColor:(int)arg1 forLevel:(long long)arg2;
- (int)quotingColorForLevel:(long long)arg1;
- (int)quotingColorValue:(id)arg1;
- (int)levelOneQuotingColor;
- (void)setLevelOneQuotingColor:(int)arg1;
- (int)levelTwoQuotingColor;
- (void)setLevelTwoQuotingColor:(int)arg1;
- (int)levelThreeQuotingColor;
- (void)setLevelThreeQuotingColor:(int)arg1;
@end

