/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class ActivityMonitor, MFError, Message, MimeBody, NSArray, NSAttributedString, NSDictionary, NSSet, NSString;

@interface MessageViewingState : NSObject
{
    NSAttributedString *_headerAttributedString;
    NSDictionary *_addressAttachments;
    NSDictionary *_plainAddresses;
    NSSet *_expandedAddressKeys;
    NSAttributedString *_attachmentsDescription;
    NSArray *_headerOrder;
    NSArray *_attachments;
    Message *_message;
    ActivityMonitor *_monitor;
    MimeBody *mimeBody;
    id document;
    MFError *error;
    long long headerIndent;
    long long headerFontAdjustmentDebt;
    int preferredAlternative;
    BOOL accountWasOffline;
    BOOL dontCache;
    BOOL showAllHeaders;
    BOOL showDefaultHeaders;
    BOOL isPrinting;
    BOOL viewSource;
    BOOL showControlChars;
    BOOL showAttachments;
    BOOL downloadRemoteURLs;
    BOOL triedToDownloadRemoteURLs;
    BOOL messageIsFromMicrosoft;
    BOOL isChildRequestForSenders;
    int displayType;
    unsigned int preferredEncoding;
    NSString *sender;
    NSString *senderName;
    NSString *childAddress;
    NSArray *requestedAddressesFromChild;
    id <MessageContentDisplay> displayer;
    id editor;
}

+ (void)initialize;
- (void)release;
- (void)dealloc;
- (id)init;
@property(retain) id editor;
- (void)editorClosed:(id)arg1;
@property(retain, nonatomic) MimeBody *mimeBody; // @synthesize mimeBody;
@property(readonly) NSArray *attachments;
@property(retain) NSAttributedString *headerAttributedString;
@property(retain) NSDictionary *plainAddresses;
@property(retain) NSDictionary *addressAttachments;
@property(retain) NSSet *expandedAddressKeys;
@property(retain) NSAttributedString *attachmentsDescription;
@property(retain) NSArray *headerOrder;
@property(readonly) int headerDetailLevel;
- (id)description;
@property(retain) ActivityMonitor *monitor; // @synthesize monitor=_monitor;
@property(retain) Message *message; // @synthesize message=_message;
@property(retain, nonatomic) id <MessageContentDisplay> displayer; // @synthesize displayer;
@property(retain, nonatomic) NSArray *requestedAddressesFromChild; // @synthesize requestedAddressesFromChild;
@property(copy, nonatomic) NSString *childAddress; // @synthesize childAddress;
@property(copy, nonatomic) NSString *senderName; // @synthesize senderName;
@property(copy, nonatomic) NSString *sender; // @synthesize sender;
@property(nonatomic) unsigned int preferredEncoding; // @synthesize preferredEncoding;
@property(nonatomic) int displayType; // @synthesize displayType;
@property(nonatomic) BOOL isChildRequestForSenders; // @synthesize isChildRequestForSenders;
@property(nonatomic) BOOL messageIsFromMicrosoft; // @synthesize messageIsFromMicrosoft;
@property(nonatomic) BOOL triedToDownloadRemoteURLs; // @synthesize triedToDownloadRemoteURLs;
@property(nonatomic) BOOL downloadRemoteURLs; // @synthesize downloadRemoteURLs;
@property(nonatomic) BOOL showAttachments; // @synthesize showAttachments;
@property(nonatomic) BOOL showControlChars; // @synthesize showControlChars;
@property(nonatomic) BOOL viewSource; // @synthesize viewSource;
@property(nonatomic) BOOL isPrinting; // @synthesize isPrinting;
@property(nonatomic) BOOL showDefaultHeaders; // @synthesize showDefaultHeaders;
@property(nonatomic) BOOL showAllHeaders; // @synthesize showAllHeaders;
@property(nonatomic) BOOL dontCache; // @synthesize dontCache;
@property(nonatomic) BOOL accountWasOffline; // @synthesize accountWasOffline;
@property(nonatomic) int preferredAlternative; // @synthesize preferredAlternative;
@property(nonatomic) long long headerFontAdjustmentDebt; // @synthesize headerFontAdjustmentDebt;
@property(nonatomic) long long headerIndent; // @synthesize headerIndent;
@property(retain, nonatomic) MFError *error; // @synthesize error;
@property(retain, nonatomic) id document; // @synthesize document;

@end

