/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSSearchField.h"

@interface MessageViewerSearchField : NSSearchField
{
    id <MessageViewerSearchFieldFocusDelegate> _focusDelegate;
    BOOL _focused;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)firstResponderDidChange:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
@property(getter=isFocused) BOOL focused;
@property id <MessageViewerSearchFieldFocusDelegate> focusDelegate; // @synthesize focusDelegate=_focusDelegate;

@end

