/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class Message, MessageThread, NSMutableSet;

@interface MessageThreadingData : NSObject
{
    Message *parent;
    NSMutableSet *replies;
    MessageThread *thread;
}

- (id)description;
- (void)dealloc;
@property(retain, nonatomic) MessageThread *thread; // @synthesize thread;
@property(retain, nonatomic) NSMutableSet *replies; // @synthesize replies;
@property(retain, nonatomic) Message *parent; // @synthesize parent;

@end

