/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

#import "MessageContentDisplay-Protocol.h"

@class NSScrollView, WebView;

@interface NoteDisplay : NSObject <MessageContentDisplay>
{
    WebView *noteView;
    NSScrollView *originalView;
    long long displayCount;
}

+ (Class)documentClass;
+ (id)copyDocumentForMessage:(id)arg1 viewingState:(id)arg2;
- (id)initWithDocument:(id)arg1;
- (void)display:(id)arg1 inContainerView:(id)arg2 replacingView:(id)arg3 invokeWhenDisplayChanged:(id)arg4;
- (void)restorePreviousDisplay;
- (void)prepareToRemoveView;
- (void)dealloc;
@property id delegate;
- (void)documentResized;
- (id)contentView;
- (id)textView;
- (id)selectedTextRepresentation;
- (void)setSelectedTextRepresentation:(id)arg1;
- (id)selectedText;
- (id)selectionParsedMessage;
- (id)attachmentsInSelection;
- (id)parsedMessage;
- (void)highlightSearchText:(id)arg1;
- (void)adjustFontSizeBy:(long long)arg1 viewingState:(id)arg2;
- (id)findTarget;
- (void)detectDataInMessage:(id)arg1 usingContext:(id)arg2;
- (void)cancelDataDetection;
@property(retain) NSScrollView *originalView; // @synthesize originalView;
@property(retain) WebView *noteView; // @synthesize noteView;

@end

