/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ComposeBackEnd.h"

@class LibraryMessage, MailAccount, NSDictionary, NSSet, NSString;

@interface NoteComposeBackEnd : ComposeBackEnd
{
    MailAccount *_account;
    NSString *_summary;
    NSString *_creationDateHeader;
    LibraryMessage *_associatedMessage;
    NSString *_backgroundColor;
    NSDictionary *_onLoadToDosByID;
    NSDictionary *_onLoadToDosByPreviousID;
    NSSet *_onLoadDeletedToDoIDs;
}

+ (void)initialize;
+ (id)supportedMailboxUidTypes;
- (void)setStateFromBackEnd:(id)arg1;
- (BOOL)isExchangeNote;
@property(retain) NSString *summary;
- (id)sender;
- (BOOL)preserveAddedArchiveBody;
@property(retain) NSString *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (BOOL)defaultFormatIsRich;
@property(retain) MailAccount *account; // @synthesize account=_account;
- (id)mailboxUidCreateIfNeeded:(BOOL)arg1;
- (id)generatedSubject;
- (void)setSubject:(id)arg1;
- (void)_backgroundSaveEnded:(id)arg1;
- (void)updateToDosInContent:(id)arg1 documentID:(id)arg2 referencedMessageID:(id)arg3;
- (id)htmlDocumentForSave;
- (id)htmlStringFromRange:(id)arg1 htmlDocument:(id)arg2 removeCustomAttributes:(BOOL)arg3 convertObjectsToImages:(BOOL)arg4 convertEditableElements:(BOOL)arg5;
- (id)outgoingMessageUsingWriter:(id)arg1 contents:(id)arg2 headers:(id)arg3 isDraft:(BOOL)arg4 shouldBePlainText:(BOOL)arg5;
- (id)saveTaskName;
@property(readonly) BOOL isPaperless;
- (BOOL)hasChanges;
- (BOOL)restoredMessageIsRich;
- (BOOL)containsRichText;
- (BOOL)saveMessage;
@property(readonly) NSString *todoDocumentID;
- (BOOL)isEditingMessage:(id)arg1;
- (void)updateDocumentReference:(id)arg1;
- (void)finishPreparingContentWithEditorSettings:(id)arg1;
- (id)description;
- (void)dealloc;
@property(retain) NSSet *onLoadDeletedToDoIDs; // @synthesize onLoadDeletedToDoIDs=_onLoadDeletedToDoIDs;
@property(retain) NSDictionary *onLoadToDosByPreviousID; // @synthesize onLoadToDosByPreviousID=_onLoadToDosByPreviousID;
@property(retain) NSDictionary *onLoadToDosByID; // @synthesize onLoadToDosByID=_onLoadToDosByID;
@property(retain) NSString *creationDateHeader; // @synthesize creationDateHeader=_creationDateHeader;
@property(retain) LibraryMessage *associatedMessage; // @synthesize associatedMessage=_associatedMessage;

@end

