/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSOperation.h"

@class ABAddressBook, NSString;

@interface RecentsSearchOperation : NSOperation
{
    NSString *_searchString;
    id _delegate;
    ABAddressBook *_addressBook;
}

- (void)main;
- (void)dealloc;
@property(retain) ABAddressBook *addressBook; // @synthesize addressBook=_addressBook;
@property(retain) id delegate; // @synthesize delegate=_delegate;
@property(retain) NSString *searchString; // @synthesize searchString=_searchString;

@end

