/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSArray, NSWindow;

@interface SheetContext : NSObject
{
    NSArray *attachments;
    NSArray *messages;
    id delegate;
    NSWindow *window;
    BOOL needsSave;
}

- (void)dealloc;
@property(nonatomic) BOOL needsSave; // @synthesize needsSave;
@property(retain, nonatomic) NSWindow *window; // @synthesize window;
@property(retain, nonatomic) id delegate; // @synthesize delegate;
@property(retain, nonatomic) NSArray *messages; // @synthesize messages;
@property(retain, nonatomic) NSArray *attachments; // @synthesize attachments;

@end

