/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "Signature.h"

@interface Signature (Applescript)
- (id)signatureName;
- (void)setSignatureName:(id)arg1;
- (id)signatureContents;
- (void)setSignatureContents:(id)arg1;
- (id)objectSpecifier;
@end

