/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

#import "NSTableViewDelegate-Protocol.h"

@class ColorBackgroundView, EmptyFavoritesMessageView, MailDocumentEditor, NSArray, NSImageView, NSMutableArray, NSMutableDictionary, NSScrollView, NSTableView, NSView, StationeryLoader, ThumbnailMatrix;

@interface StationerySelector : NSObject <NSTableViewDelegate>
{
    NSTableView *categoriesTableView;
    ThumbnailMatrix *thumbnailMatrix;
    MailDocumentEditor *documentEditor;
    NSView *selectorPane;
    ColorBackgroundView *horizontalScrollerBackground;
    EmptyFavoritesMessageView *emptyFavoritesMessageView;
    NSScrollView *thumbnailsScrollView;
    NSImageView *thumbnailLeftSideShadowView;
    double minimumScrollViewContentOriginX;
    StationeryLoader *stationeryLoader;
    NSArray *categoryDictionaries;
    NSArray *stationeryDictionaries;
    NSMutableArray *deletedStationery;
    NSMutableDictionary *scrollPositionByCategory;
    BOOL isFirstShowOfCategoriesForFavorites;
    BOOL isFirstShowOfCategoriesForExistingStationery;
    BOOL hasRegisteredForNewThumbnailImageNotifications;
}

- (id)init;
- (void)awakeFromNib;
- (void)dealloc;
- (double)stationeryPaneHeight;
- (double)horizontalScrollerWidth;
- (double)scrollerValue;
- (double)scrollerProportion;
- (void)showStationery;
- (void)refreshStationery;
- (void)stationeryDidChange:(id)arg1;
- (BOOL)selectionShouldChangeInTableView:(id)arg1;
- (void)selectCategory:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)saveThumbnailScrollPosition;
- (void)restoreThumbnailScrollPosition;
- (void)displayStationery:(id)arg1 showDeleteButtons:(BOOL)arg2 beginningAtIndex:(long long)arg3;
- (void)setStationeryDictionaries:(id)arg1;
- (void)selectStationery:(id)arg1;
- (void)clearStationerySelection;
- (void)deleteStationery:(id)arg1;
- (void)startDragSessionFromIndex:(long long)arg1 withImage:(id)arg2 event:(id)arg3;
- (BOOL)handleDropIntoFavorites;
- (void)thumbnailImageIsAvailable:(id)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (unsigned long long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (BOOL)draggingPasteboardContainsStationery;
- (void)thumbnailsDidScroll:(id)arg1;

@end

