/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSDatePicker.h"

@interface ToDoMenuDatePicker : NSDatePicker
{
}

+ (id)menuDatePicker;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setPosition:(long long)arg1;
- (long long)position;

@end

