/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSView.h"

@class NSTextField, ToDoMultipleAlarmsView, ToDoPlusMinusButton;

@interface ToDoAlarmEditorView : NSView
{
    ToDoMultipleAlarmsView *_alarmsView;
    ToDoPlusMinusButton *_addAlarmButton;
    NSTextField *_addAlarmLabel;
    NSTextField *_otherAlarmsText;
    ToDoPlusMinusButton *_otherAlarmsClearButton;
    double _addAlarmSectionHeight;
    double _otherAlarmsSectionHeight;
    double _verticalInset;
    BOOL _enabled;
    id <ToDoAlarmEditorViewDelegate> _delegate;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (void)drawRect:(struct CGRect)arg1;
- (void)finishInitialLayout;
- (BOOL)_canAddAlarm;
- (void)reLayout;
- (void)alarmsLayoutChanged:(id)arg1;
- (void)setAlarms:(id)arg1;
- (id)alarms;
- (void)setOtherAlarmsLabel:(id)arg1;
- (void)setOtherAlarmsHidden:(BOOL)arg1;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
- (void)setCustomOffsetTypeEnabled:(BOOL)arg1;
@property id <ToDoAlarmEditorViewDelegate> delegate; // @synthesize delegate=_delegate;

@end

