/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSWindow.h"

@class TypeAheadResponder;

@interface TypeAheadWindow : NSWindow
{
    TypeAheadResponder *_typeAheadResponder;
    BOOL sendMouseDownNotifications;
}

- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4 screen:(id)arg5;
- (void)dealloc;
- (void)setTypeAheadInitialFirstResponder;
- (void)sendEvent:(id)arg1;
- (void)sendMouseDownNotifications:(BOOL)arg1;
- (void)flushTypeAheadEvents;

@end

