/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

#import "QueryProgressMonitor-Protocol.h"

@interface UnreadQueryProgressMonitor : NSObject <QueryProgressMonitor>
{
    unsigned long long sequenceNumber;
    long long librarySequenceNumber;
}

- (id)initWithSequenceNumber:(unsigned long long)arg1 librarySequenceNumber:(long long)arg2;
- (BOOL)shouldCancel;

@end

