/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSString;

@interface VisibleStateObject : NSObject
{
    BOOL hadSelection;
    BOOL selectionWasVisible;
    BOOL scrollerWasAtEnd;
    BOOL forceSelToVisible;
    NSString *msgIDToPin;
    double msgUpperLeft;
    NSMutableDictionary *selectedMessageIDs;
    NSArray *openThreadIDs;
}

- (void)dealloc;
@property(retain, nonatomic) NSArray *openThreadIDs; // @synthesize openThreadIDs;
@property(retain, nonatomic) NSMutableDictionary *selectedMessageIDs; // @synthesize selectedMessageIDs;
@property(nonatomic) double msgUpperLeft; // @synthesize msgUpperLeft;
@property(retain, nonatomic) NSString *msgIDToPin; // @synthesize msgIDToPin;
@property(nonatomic) BOOL forceSelToVisible; // @synthesize forceSelToVisible;
@property(nonatomic) BOOL scrollerWasAtEnd; // @synthesize scrollerWasAtEnd;
@property(nonatomic) BOOL selectionWasVisible; // @synthesize selectionWasVisible;
@property(nonatomic) BOOL hadSelection; // @synthesize hadSelection;

@end

