/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "WebFrameView.h"

@interface WebFrameView (MailExtras)
+ (void)swizzleKeyDown;
- (BOOL)_mail_scrollVerticallyBy:(double)arg1;
- (double)_mail_verticalPageScrollDistance;
- (double)_mail_verticalKeyboardScrollDistance;
- (BOOL)_mail_scrollHorizontallyBy:(double)arg1;
- (double)_mail_horizontalKeyboardScrollDistance;
@end

